echo "hello world" && ls -l && pwd
cd ..
git clone https://github.com/CityScope/CS_Brix.git
cp -r CS_Brix/docs/markdown action-target/cs_brix/docs/markdown
cd action-target
echo "running git actions"
git status
echo "adding files"
git add cs_brix/docs/markdown/.
git status
echo "commiting"
git commit -m "autogenerated update $(date +"%T")"
echo "pushing"
git push
echo "DONE"
