# Description: Workflow that checks if CityIO is down every 10 minutes, and creates and issue when it's down. 
# Author: Cristian Jara-Figueroa, Phd Student MIT Media Lab
# Last updated: November 3, 2020
name: Comment on down

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check CityIO Status
        run: curl --fail http://cityio.media.mit.edu || exit 1
      - uses: JasonEtco/create-an-issue@v2
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
