name: Action test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # schedule:
    # - cron:  '30 * * * *' # at 30 minutes
    # - cron:  '* * * * *' # once a minute

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test things
          run: 
            shell: bash
            shell: ls -l