name: Action test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # schedule:
    # - cron:  '30 * * * *' # at 30 minutes
    # - cron:  '* * * * *' # once a minute

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test things
        run: bash update.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: crisjf
          author_email: crisjf@mit.edu
          message: "Commit from actions $(date +"%T")"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
