name: Update docs

on:
  # push:
    # branches: [ master ]
  # pull_request:
    # branches: [ master ]
  schedule:
    - cron:  '0 0 * * *' # Everyday at midnight
  workflow_dispatch:
  repository_dispatch:
    types: [docs_update]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update CS_Brix
        run: bash .github/scripts/update.sh CityScope CS_Brix docs/markdown/docusaurus.md docsite/docs/backend

      # SYNTAX TO ADD REPOS
      # - name: Update REPO_NAME
        # run: bash .github/scripts/update.sh REPO_NAME_OWNER REPO_NAME PATH_TO_FILE(README.md IS DEFAULT) DESTINATION_PATH(docsite/docs is defauls)

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: crisjf
          author_email: crisjf@mit.edu
          message: "Commit from actions"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
