# Description: Workflow that updates markdown files by fetching them from other repositories. It runs every day at midnight automatically, or it can be triggered manually or by setting up a dispatch action in the lower level repo.
# Author: Cristian Jara-Figueroa, Phd Student MIT Media Lab
# Last updated: November 3, 2020
name: Comment on down

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check CityIO Status
        run: curl --fail http://cityio.media.mit.edu
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ failure() }}
        with:
          issue-number: 1
          body: |
            CityIO is down...
