name: Action test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # schedule:
    # - cron:  '30 * * * *' # at 30 minutes
    # - cron:  '* * * * *' # once a minute

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test things
        run: bash update.sh
